# Generated by Django 4.2 on 2023-04-08 00:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('file_name', models.TextField()),
                ('authors', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='ScientificPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'scientific_publications',
            },
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian', models.TextField()),
                ('english', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'strings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.TextField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('confirmed', models.BooleanField(default=False)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_name', to='journal_website.string')),
                ('scientific_publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volume_scientific_publication', to='journal_website.scientificpublication')),
            ],
            options={
                'verbose_name_plural': 'volumes',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_url_address', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_page_name', to='journal_website.string')),
            ],
            options={
                'verbose_name_plural': 'static_pages',
            },
        ),
        migrations.CreateModel(
            name='ScientificSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_specialty_name', to='journal_website.string')),
                ('science_branches', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientific_specialty_science_branches', to='journal_website.staticpage')),
            ],
            options={
                'verbose_name_plural': 'scientific_specialties',
            },
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientific_publication_contacts', to='journal_website.staticpage'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='contract_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientific_publication_contract_information', to='journal_website.staticpage'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='editorial_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientific_publication_editorial_team', to='journal_website.staticpage'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_publication_full_name', to='journal_website.string'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='legal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientific_publication_legal_information', to='journal_website.staticpage'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='main_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientific_publication_main_editor', to='journal_website.staticpage'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='science_branches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scientific_publication_science_branches', to='journal_website.staticpage'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='short_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_publication_short_name', to='journal_website.string'),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='founder_contacts', to='journal_website.staticpage')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder_full_name', to='journal_website.string')),
                ('scientific_publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='founder_scientific_publication', to='journal_website.scientificpublication')),
            ],
            options={
                'verbose_name_plural': 'founders',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('publication_date', models.DateField()),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_article', to='journal_website.article')),
            ],
            options={
                'verbose_name_plural': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='journal_website.string')),
                ('scientific_publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_scientific_publication', to='journal_website.scientificpublication')),
                ('scientific_specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_scientific_specialty', to='journal_website.scientificspecialty')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_category', to='journal_website.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_name', to='journal_website.string'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_short_description', to='journal_website.string'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_custom_user', to='journal_website.user'),
        ),
        migrations.AddField(
            model_name='article',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_volume', to='journal_website.volume'),
        ),
    ]
