# Generated by Django 4.2 on 2023-04-13 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_category', to='journal_website.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_custom_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_volume', to='journal_website.volume'),
        ),
        migrations.AlterField(
            model_name='category',
            name='scientific_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scientific_publication', to='journal_website.scientificpublication'),
        ),
        migrations.AlterField(
            model_name='category',
            name='scientific_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scientific_specialty', to='journal_website.scientificspecialty'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_contacts', to='journal_website.staticpage'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='scientific_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder_scientific_publication', to='journal_website.scientificpublication'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_publication_contacts', to='journal_website.staticpage'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='contract_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_publication_contract_information', to='journal_website.staticpage'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='editorial_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_publication_editorial_team', to='journal_website.staticpage'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='legal_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_publication_legal_information', to='journal_website.staticpage'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='main_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_publication_main_editor', to='journal_website.staticpage'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='science_branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_publication_science_branches', to='journal_website.staticpage'),
        ),
        migrations.AlterField(
            model_name='scientificspecialty',
            name='science_branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_specialty_science_branches', to='journal_website.staticpage'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='scientific_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_scientific_publication', to='journal_website.scientificpublication'),
        ),
    ]
