# Generated by Django 4.2 on 2023-04-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_website', '0003_alter_userpersonaldata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonaldata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userpersonaldata',
            name='password',
        ),
    ]
