# Generated by Django 4.2 on 2023-04-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_website', '0004_remove_userpersonaldata_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonaldata',
            name='nickname',
        ),
    ]
