# Generated by Django 4.2 on 2023-04-08 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal_website', '0005_remove_userpersonaldata_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user_additional_data',
            },
        ),
        migrations.DeleteModel(
            name='UserPersonalData',
        ),
    ]
