# Generated by Django 4.2 on 2023-04-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_website', '0006_useradditionaldata_delete_userpersonaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditionaldata',
            name='code',
        ),
        migrations.RemoveField(
            model_name='useradditionaldata',
            name='confirmed',
        ),
    ]
