# Generated by Django 4.2 on 2023-04-10 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journal_website', '0007_remove_useradditionaldata_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionaldata',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
