version: "3.0"

services:
  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-rc-management
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_DEFAULT_USER=simple_user
      - RABBITMQ_DEFAULT_PASS=simple_password
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    hostname: rabbitmq

  # WEB
  django:
    build: .
    command: python3.11 manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - media_volume:/website/journal_website/media
      - static_volume:/website/journal_website/static
      - database_volume:/website/journal_website/database
    ports:
      - "8000:8000"
    image: django-image
    network_mode: "host"
    depends_on:
      - rabbitmq

  # Celery worker
  celery_worker:
    command: celery -A website worker -l info
    container_name: celery_worker
    image: django-image
    depends_on:
      - rabbitmq
      - django

volumes:
  media_volume:
  static_volume:
  database_volume: