version: "3"

services:
  django:
    build: .
    volumes:
      - media_volume:/website/journal_website/media
      - static_volume:/website/journal_website/static
      - database_volume:/website/db.sqlite3
    ports:
      - "8000:8000"

volumes:
  media_volume:
  static_volume:
  database_volume: